### ISSUE TITLE
Allow configuring to skip AccquireInformation as first view

### ISSUE THREAD

**Issue by gobengo** [erxes/erxes-widgets#100]
I'd love to allow anonymous use of Messenger without the user first seeing "Give us your contact information".

Can I let them skip?

**Comment by shinebayar-g** [comment]
Hi, I'll ask this from our team and will keep you update. Thanks.

**Comment by shinebayar-g** [comment]
This option will be added in next week

**Comment by gobengo** [comment]
Awesome! @shinebayar-g Thank you team

**Comment by batamar** [comment]
@gobengo #104

**Comment by gobengo** [comment]
@batamar @shinebayar-g  How do I define `requireAuth` from my erxes JavaScript embed? I'm just defining `window.erxesSettings`.

**Comment by batamar** [comment]
@gobengo https://docs.erxes.io/docs/support-guide#setup-messenger-integration

**Comment by veerjainATgmail** [comment]
The link provided has changed..thanks.    https://docs.erxes.io/docs/user/support
