### ISSUE TITLE
[Enhancement] Messanger - agent feedback

### ISSUE THREAD

**Issue by veerjainATgmail** [erxes/erxes-widgets#131]
**Is your feature request related to a problem? Please describe.**
Agent feedback/Rating

**Describe the solution you'd like**
The conversation message could have an option for a live agent to nudge customer for rating for the interaction, which is added to the agent data. (NPS net promotor score.)

**Describe alternatives you've considered**
none

**Additional context**
none.

**Comment by mendorshikh** [comment]
Hey @veerjainATgmail 

This feature will be live in two weeks. We already developed it on knowledgebase. In two weeks or less, it will be on messenger.

**Comment by veerjainATgmail** [comment]
@mendorshikh , Thats Awesome :+1: :fireworks:
