### ISSUE TITLE
Launch messenger widget programatically on web

### ISSUE THREAD

**Issue by kalyankuramana** [erxes/erxes-widgets#148]
Problem: 
1) As part of the support system inside the web, it is always difficult to fix the position of launcher icon to the bottom, especially on mobile, since it overlaps with other elements, especially bottom navbar.
2) Say the launcher icon is loaded on home page on a  single page app where games are listed, it is disturbing to show the launcher icon on the gameplay page as well. Since it  is attached to the scope of the body, it  will  remain on  other pages as  well, since its a single page app

Solution:
1) It would be great if a messenger can be launched programmatically like erxes.launch() on some user interaction, "like clicking on request for help button". 
2) Rather than attaching to document,  there should be an option to attach the erxes launcher to a specific element, as it causes the problem in single-page apps since it is not ideal to display the launcher icon in every page.

**Additional context**
See the image below, It would be great when messenger can be launched when user clicks on help button. 
<img width="605" alt="Screen Shot 2019-11-01 at 12 24 06 PM" src="https://user-images.githubusercontent.com/753138/68008282-63295500-fca4-11e9-9bd5-d9fdfbdfb3cd.png">

**Comment by batamar** [comment]
@kalyankuramana thanks for the detailed explanation. I agree that it is a very common use case. So After implementing this feature, we will let you know

**Comment by batamar** [comment]
Hi @kalyankuramana. We implemented this feature. Now you can follow the below steps to accomplish your needs

1. Uncheck show launcher check to hide default handler
<img width="1592" alt="Screen Shot 2020-01-08 at 12 26 58 AM" src="https://user-images.githubusercontent.com/1748899/71910916-c1dfe300-31ad-11ea-9bf0-73150accc873.png">

2. There is a showErxesMessenger function available on the window object. You can use this function to show messenger programmatically.
```
window.showErxesMessenger()
```

3. You can manipulate the position of the messenger body like following
```
#erxes-messenger-container {
   top: 0px;
   left: 55%;
}
```
<img width="412" alt="Screen Shot 2020-01-08 at 12 32 38 AM" src="https://user-images.githubusercontent.com/1748899/71911283-64986180-31ae-11ea-8dcd-5b5298070ae5.png">

**Comment by kalyankuramana** [comment]
Hi Battulga,

wow, that's awesome. It definitely helps
