### ISSUE TITLE
Add new language files

### ISSUE THREAD

**Issue by batamar** [erxes/erxes-widgets#79]

**Comment by MarceloFigueira** [comment]
como assim nova lingua?

**Comment by batamar** [comment]
@MarceloFigueira Add new language file in locales folder like en.json

**Comment by batamar** [comment]
Create new branch from develop branch

**Comment by MarceloFigueira** [comment]
Ok it's done

**Comment by Janice0218** [comment]
can i do it?

**Comment by thanhcng** [comment]
I would like to add Vietnamese language please

**Comment by thanhcng** [comment]
I would like to add support for Vietnamese language please!
